# -*- coding: utf-8 -*-
"""Face_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vnp1a7BtsuuKA6qCVsLZJyOTeMimP7T
"""

"""- Tải các thư viện cần thiết


- Uploaded file 'haarcascade_frontalface_default.xml'
"""

import cv2
import numpy as np

# Haarcascade file path (make sure this file is uploaded)
haar_file = 'c:/Users/ADMIN/Desktop/PythonCoding/openCV/haarcascade_frontalface_default.xml'

# Load the image from your uploaded file
img_path = 'c:/Users/ADMIN/Desktop/PythonCoding/openCV/asset/chair.jpg'  # Update with your image path
image = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
num_of_face_detected = 0

if image is None:
    print("Image not loaded correctly.")
else:
    # Convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Load Haarcascade for face detection
    face_cascade = cv2.CascadeClassifier(haar_file)

    # Detect faces
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    # Draw ellipse around faces
    for (x, y, w, h) in faces:
        center_x = x + w // 2
        center_y = y + h // 2
        radius_x = w // 2
        radius_y = h // 2
        cv2.ellipse(image, (center_x , center_y), (radius_x, radius_y), 0, 0, 360, (255, 0, 255), 2)
        num_of_face_detected += 1


    # Show the image with detected faces
    cv2.imshow('Image', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    print("Number of faces detected: ", num_of_face_detected)